export const FIND_BILLINGS = 'FIND_BILLINGS';

export const GET_BILLING = 'GET_BILLING';

export const UPDATE_BILLING = 'UPDATE_BILLING';

export const CREATE_BILLING = 'CREATE_BILLING';

export const CREATE_BILLING_ITEM = 'CREATE_BILLING_ITEM';

export const UPDATE_BILLING_ITEM = 'UPDATE_BILLING_ITEM';

export const REMOVE_BILLING_ITEM = 'REMOVE_BILLING_ITEM';
