export const FIND_INVOICES = 'FIND_INVOICES';

export const GET_INVOICE = 'GET_INVOICE';

export const UPDATE_INVOICE = 'UPDATE_INVOICE';

export const CREATE_INVOICE = 'CREATE_INVOICE';

export const CREATE_INVOICE_ITEM = 'CREATE_INVOICE_ITEM';

export const UPDATE_INVOICE_ITEM = 'UPDATE_INVOICE_ITEM';

export const REMOVE_INVOICE_ITEM = 'REMOVE_INVOICE_ITEM';
